<?php


namespace App\Controller\Admin;


use NeutronStars\Neutrino\Core\Controller;

class AdminController extends Controller
{
    public function __construct(bool $check = true)
    {
        if($check){
            $this->redirect('admin.login');
        }
    }

    public function admin()
    {
        $this->render('admin.home');
    }
    protected function render(string $view, array $params = [], string $layout = 'admin.index'): void
    {
        parent::render($view, $params, $layout); // TODO: Change the autogenerated stub
    }

}