<?php


namespace App\Controller\Admin;


use App\Entity\User;
use App\Model\UsersModel;
use NeutronStars\Neutrino\Core\Controller;
use NeutronStars\Neutrino\Core\Kernel;

class AdminController extends Controller
{
    public function __construct(bool $check = true)
    {
        /*(new UsersModel())->insert();*/ // Ajout d'un admin sans formulaire UserModel ligne 55
        if($check && !$this->isConnected()){
            $this->redirect('admin.login');
        }
    }

    public function admin()
    {
        $this->render('admin.home');
    }
    protected function render(string $view, array $params = [], string $layout = 'admin.index'): void
    {
        parent::render(
            $view, $params + [
                'isConnected'=>$this->isConnected(),
                'user'=>$this->getUser()
            ], $layout
        ); // TODO: Change the autogenerated stub
    }
    protected function connect(User $user)
    {
        $_SESSION['auth_user']=[];
        $_SESSION['auth_user']['id']=$user->getId();
        $_SESSION['auth_user']['timeout']=time();
    }
    protected function disconnect()
    {
        unset($_SESSION['auth_user']);
    }
    protected function isConnected():bool
    {
        return Kernel::get()->isConnected;
    }
    protected function getUser():?User
    {
        return Kernel::get()->user;
    }

}