<?php


namespace App\Controller;


use NeutronStars\Neutrino\Core\Controller;

class TournoisController extends Controller
{
    public function tournois ()
    {
        $this->render('app.tournois');
        /*$this->render('app.tournois',[
            "pageTournois"=>true
        ]); reecriture de render*/
    }
    public function valhallacup ()
    {
        $this->render('app.valhallacup');
    }
    public function valhallakidz ()
    {
        $this->render('app.valhallakidz');
    }
    /* reecriture de la function render */
    protected function render(string $view, array $params = [], string $layout = 'index'): void
    {
        parent::render($view, $params + ["pageTournois"=>true], $layout); // TODO: Change the autogenerated stub
    }
}